#
#  Makefile for Examples, Chapter 5
#

all: chars copy copy2 lines strip

chars: chars.c
	gcc -o chars chars.c

copy: copy.c
	gcc -o copy copy.c

copy2: copy2.c
	gcc -o copy2 copy2.c

lines: lines.c
	gcc -o lines lines.c

strip: strip.c
	gcc -o strip strip.c


clean: 
	rm chars copy copy2 lines strip
