#
#  Makefile for Examples, Chapter 16
#

all: localtime showtime

localtime: localtime.c
	gcc -o localtime localtime.c

showtime: showtime.c
	gcc -o showtime showtime.c

clean: 
	rm localtime showtime
