#
#  Makefile for Solutions, Chapter 5
#

all: 5-1 5-2 5-3 5-4

5-1: 5-1.c
	gcc -o 5-1 5-1.c

5-2: 5-2.c
	gcc -o 5-2 5-2.c

5-3: 5-3.c
	gcc -o 5-3 5-3.c

5-4: 5-4.c
	gcc -o 5-4 5-4.c

clean: 
	rm 5-1 5-2 5-3 5-4
