#
#  Makefile for Solutions, Chapter 2
#

all: 2-3 2-4 2-5 2-6

2-3: 2-3.c
	gcc -o 2-3 2-3.c

2-4: 2-4.c
	gcc -o 2-4 2-4.c

2-5: 2-5.c
	gcc -o 2-5 2-5.c

2-6: 2-6.c
	gcc -o 2-6 -lm 2-6.c     # -lm = link with math library

clean: 
	rm 2-3 2-4 2-5 2-6
