#
#  Makefile for Solutions, Chapter 8 
#

all: 8-1 8-2 8-3 8-4

8-1: 8-1.c
	gcc -o 8-1 8-1.c

8-2: 8-2.c
	gcc -o 8-2 8-2.c

8-3: 8-3.c
	gcc -o 8-3 8-3.c

8-4: 8-4.c
	gcc -o 8-4 8-4.c

clean: 
	rm 8-1 8-2 8-3 8-4
