#
#  Makefile for Examples, Chapter 6 
#

all: declaration extended prototype

declaration: declaration.c
	gcc -o declaration declaration.c

extended: extended.c
	gcc -o extended extended.c

prototype: prototype.c
	gcc -o prototype prototype.c

clean: 
	rm declaration extended prototype
