#
#  Makefile for Examples, Appendix B 
#

all: delim printenv mygrep digits

delim: delim.c
	gcc -o delim delim.c

printenv: printenv.c
	gcc -o printenv printenv.c

mygrep: mygrep.c
	gcc -o mygrep mygrep.c

digits: digits.c
	gcc -o digits digits.c

clean: 
	rm delim printenv mygrep digits
