#
#  Makefile for Examples, Chapter 4
#

all: conditional define square

conditional: conditional.c
	gcc -o conditional conditional.c

define: define.c
	gcc -o define define.c

square: square.c
	gcc -o square square.c

clean: 
	rm conditional define square
