#
#  Makefile for Examples, Chapter 15 
#

all: errs fopen fclose scanf

errs: errs.c
	gcc -o errs errs.c

fopen: fopen.c
	gcc -o fopen fopen.c

fclose: fclose.c
	gcc -o fclose fclose.c

scanf: scanf.c
	gcc -o scanf scanf.c

clean: 
	rm errs fopen fclose scanf
